version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt > ./VERSION
         git add --all
         git commit -m "new version"
         git push origin $CIRCLE_BRANCH
