version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: |
         VERSION=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
         docker login -u $DOCKER_USER -p $DOCKER_PASS
         docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_USERNAME:$VERSION .
         docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_USERNAME:$VERSION
