version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt > ./VERSION
          git config --global user.email "ops@nalbam.com"
          git config --global user.name "bot"
          git add --all
          git commit -m "new version"
          git push origin $CIRCLE_BRANCH

workflows:
  version: 2
  nightly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
